from tree import MinMaxTree

if __name__ == "__main__":
	tree = MinMaxTree(True, './minmaxtree.bin')
	tree.printBoard()

	# VARIOS TESTES REALIZADOS, MOSTRA BASICAMENTE O FUNCIONAMENTO DA ARVORE
	# RECOMENDO LER COMENTARIOS NA LIB

	# tree.registerMove(0,2)
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMove(2,0)
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMove(2,1)
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMove(0,0)
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()

	# tree.registerMove(0,2)
	# tree.registerMove(0,0)
	# tree.registerMove(2,2)
	# tree.registerMove(1,2)
	# tree.registerMove(1,0)
	# tree.registerMove(0,1)
	# tree.registerMove(1,1)
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()

	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMove(2,2)
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMove(0,1)
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMove(1,1)
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()

	# tree.registerMove(0,0)
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMove(2,0)
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMove(1,2)
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMove(2,1)
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()

	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()
	# tree.registerMoveIA(tree.searchBestMove())
	# tree.printBoard()

